---
exp_name: 1  # ---> 1,2,3,4,5...
exp_dir: ../exp/2D_ARG/MLP/CIFAR100  # ---> 0421_mlp_cifar_expMode

runner: XorNeuronRunner
use_gpu: True
gpus: [0]
seed: 1101 # 1101 ~ 1124

# ---- EXP Mode ---- #
without_pretrain: False # ---> xavier_inner_net
to_save_cell: False  # ---> save epoch by epcoh

dataset:
  name: cifar100
  loader_name: InnerNetData   # exp 1D ---> InnerNetData_1D
  data_path: ./xor_neuron_data/data
  split: train

model:
  name: ComplexNeuronMLP
  num_cell_types: 1
  inner_net: mlp
  input_dim: 3072 #784(mnist)/3072(cifar10)
  arg_in_dim: 2
  in_hidden_dim: 64
  out_hidden_dim: [64, 64, 64] # [132, 132, 132]
  dropout: 0.5
  num_classes: 100
  loss: CrossEntropy

pretrain:
  optimizer: Adam
  num_workers: 0
  max_epoch: 500  # ---> 1D-arg: 50000   2D-arg: 500
  batch_size: 100
  snapshot_epoch: 1000
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  best_model: [ /model_snapshot_best_pretrained1.pth]

train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 0
  max_epoch: 200
  batch_size: 100
  display_iter: 5000
  snapshot_epoch: 1000
  valid_epoch: 1
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
  best_model: /model_snapshot_best_phase1.pth

test:
  batch_size: 100
  num_workers: 0
  test_model: /model_snapshot_best_phase2.pth