---
exp_name: 1  # ---> 1,2,3,4,5...
exp_dir: ../Control_activation_fnc_EXP/Conv/CIFAR10  # ---> 0421_conv_cifar_expMode

runner: XorNeuronRunner
use_gpu: true
gpus: [3]
seed: 246820

# ------------------------------------------#
without_pretrain: False
to_save_cell: False
# ------------------------------------------#

pretrain: None

dataset:
  name: cifar10
  loader_name: InnerNetData
  data_path: /workspace/xor_neuron_ver2/xor_neuron/xor_neuron_data/data
  split: train

model:
  name: Control_Conv
  input_channel: 3 # 1(mnist)/3(cifar10)
  out_channel: [120,150,170,170] #[66, 132, 132, 126]
  kernel_size: [3, 3, 3, 1]
  zero_pad: [0, 0, 0, 0]
  stride: [1, 1, 1, 1]
  dropout: 0.5
  num_cell_types: 1
  activation_fnc: ReLU # ELU, LeakyReLU, PReLU, SELU, CELU, GELU, SiLU

train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 0
  max_epoch: 200
  batch_size: 256
  display_iter: 5000
  snapshot_epoch: 1000
  valid_epoch: 1
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
  best_model: /model_snapshot_best_control.pth

test:
  batch_size: 256
  num_workers: 0
  test_model: /model_snapshot_best_control.pth