---
exp_name: 1 # ---> 1,2,3,4,5...
exp_dir: ../Resnet20_activation_fnc_EXP2/ # ---> 0421_conv_cifar_expMode

runner: XorNeuronRunner
use_gpu: true
gpus: [0]
seed: 1101 # 1101 ~ 1124

# ---- EXP Mode ---- #
without_pretrain: False # ---> True: xavier_inner_net
to_save_cell: False  # ---> save epoch by epcoh

dataset:
  name: cifar10  # cifar100
  loader_name: InnerNetData   # exp 1D ---> InnerNetData_1D
  data_path: ./xor_neuron_data/data
  split: train
  augmentation: True

model:
  name: resnet20
  num_cell_types: 1
  inner_net: conv
  input_channel: 3 # 1(mnist)/3(cifar10)
  arg_in_dim: 2
  in_channel: 16
  activation_fnc: ReLU # ELU, LeakyReLU, PReLU, SELU, CELU, GELU, SiLU

#  out_channel: [60, 120, 120, 120] #[66, 132, 132, 126]
#  kernel_size: [3, 3, 3, 1]
#  zero_pad: [0, 0, 0, 0]
#  stride: [1, 1, 1, 1]
  num_blocks: [3,3,3]

  dropout: 0.5
  num_classes: 10
  loss: CrossEntropy

pretrain:
  optimizer: Adam
  num_workers: 0
  max_epoch: 20  # ---> 1D-arg: 50000   2D-arg: 500
  batch_size: 100
  snapshot_epoch: 1000
  lr: 1.0e-3
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  best_model: [ /model_snapshot_best_pretrained1.pth]

train:
  optimizer: SGD
  lr_decay: 0.0001
  lr_decay_steps: [10000]
  num_workers: 0
  max_epoch: 400
  batch_size: 512
  display_iter: 5000
  snapshot_epoch: 1000
  valid_epoch: 1
  lr: 1.0e-2
  wd: 1.0e-2
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None
  best_model: /model_snapshot_best_control.pth

test:
  batch_size: 128
  num_workers: 0
  test_model: /model_snapshot_best_control.pth